before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^typo'

brews:
  -
 #    name: myproject

    tap:
      owner: zytek
      name: homebrew-tools
      # Optionally a token can be provided, if it differs from the token provided to GoReleaser
      #token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: goreleaserbot
      email: noreply@nuxi.pl

    # Folder inside the repository to put the formula.
    # Default is the root folder.
    folder: Formula

    # Caveats for the user of your binary.
    # Default is empty.
    caveats: "You need to configure this software before use (goship configure or check docs)"
    homepage: "https://github.com/zytek/goship"
    description: "Utility that helps find, connect  and copy to particular cloud resources using configured providers"
    license: "MIT"
    skip_upload: false

    dependencies: []

    test: |
      system "#{bin}/goship version"

    install: |
      bin.install "goship"
